---
title: "R Notebook"
output: html_notebook
---

## Microsatellite Genetic Analysis Workflow

This document exists to explain the steps in the msat genetic analysis workflow, specifically for the RPBB population genetics project. However, it's intended to also remind me (and hopefully others) how to do these things for other projects in the future.

The workflow assumes you have...

-   Genotypes already (in this case, in a file provided by USDA)
-   Various metadata files from field collections of the specimens

## Various issues

- There are five specimens marked as NA for sex from Genevieve Pugesek. What to do with these?
    - From poking at their genotypes, they appear to be largely homozygous...it's possible they're males...but they are not completely homozygous...
    - `r emo::ji("warning")`Revisit `r emo::ji("warning")` For now, I have chosen to exclude them
- B126 was erroneously named BT126 in the error rate file from USDA (but named B126_1 and B126_2 in the columns of the genotype sheet). Ensure this switch (from BT126 -> B126) is the correct name rather than the other way around (i.e. BT126 being correct)
- Would be nice if the names of the clusters meant something (so renaming them from current random numbers)
- `r emo::ji("warning")``r emo::ji("warning")``r emo::ji("warning")`the output of COLONY is very suspect!!! 
    - have various approaches I'm trying to correct this
- `r emo::ji("warning")`currently trying 03a geneind object with and without removal of siblings...
- `r emo::ji("warning")`Cluster number does not always match expected when 01d is loaded...this could just be due to filtering that occurs afterwards though (min loci, sex)  
    - this apparently is not a good note because I don't recall what it means...check 01d
- `r emo::ji("warning")` Check for HWE and LD among markers...maybe this will help with COLONY?

## Various things to do

- In 2022-12-15 I stopped after re-wrangling the 01 series (folding in Jay's updated metadata, making clusters for multiple buffers); resume this work by creating COLONY sub lists and making .DAT files in R (basically want to "automate" this a little bit in a way that's easy to re-do and backtrack if needed)
- Check for HWE
- Check for LD




## Steps

Note - corresponding files are named to reflect the numbering here (e.g. the file for merging metadata is "01a..." reflecting it's from section 1 item a)

### 01. Merging metadata and genotype data

a. Merge metadata sources
b. Wrangle metadata and clean names of various parameters
c. Spatial clustering of points to assign populations
d. Merge metadata with genotype data

### 02. Running COLONY and wrangling outputs

a. Prepare COLONY input files
b. Make DAT file for COLONY; Run COLONY (done outside of R on command line)
c. Wrangle COLONY outputs


### 03. Running various population genetic analysis

a. Create geneind object and run quality checks
b. Various popgen analysis
    - summary stats, HE vs. HO, F-stats


### 04. Additional analyses

a. Colony Abundance
b. Separation distances
c. etc...